### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 1003520                                             # 1280*28*28
video_max_pixels: 1003520
trust_remote_code: true
# infer_backend: vllm

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: train/examples/deepspeed/ds_z3_config.json

### dataset
dataset: vqa_cold_start,maze_cold_start,GPT4Scene_cold_start,SR_91k_cold_start
dataset_dir: /path/to/ViLaSR-data          
template: qwen2_vl
cutoff_len: 18432 # 2048
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 96 # 16
dataloader_num_workers: 32 # 4
# mask_history 是否仅使用当前对话轮次进行训练。default: False

### output
output_dir: checkpoints/cold_start/qwen2_5_vl-7b_vilasr_cold_start_32gpu
logging_steps: 10
save_steps: 200
save_total_limit: 1       # new
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
